### ISSUE TITLE
Inbox message cleaning

### ISSUE THREAD

**Issue by StevenPuttemans** [opencv-infrastructure/answers.opencv.org#1]
In previous AskBot version you could select messages seperately and delete them if wanted. Now there is only a button to clear the unread options but no way to get back to the list once the messages are selected. The red envelop disappears and no gray envelop appears.

Also it seems that the button only deactivates the red flag, but the message list keeps growing in my account!

**Comment by alekcac** [comment]
Please try one more time, it should be fixed now.
