### ISSUE TITLE
removing answer from moderation tool does not reset counter

### ISSUE THREAD

**Issue by berak** [opencv-infrastructure/answers.opencv.org#11]
when we remove a spam answer from the moderation page (instead of going to the question page and delete it), answer count is still at 1.

http://answers.opencv.org/question/70140/how-to-remove-detected-shadows-from-foreground-image-in-the-light-projector/

harmless, but confusing.

**Comment by StevenPuttemans** [comment]
@berak is this solved in the meanwhile? I do think so.
