### ISSUE TITLE
Spam on the admin mailing address

### ISSUE THREAD

**Issue by StevenPuttemans** [opencv-infrastructure/answers.opencv.org#13]
I get frequent mails now of someone responding to topics using the report button.
I have the idea that this is auto generated. Could we avoid this somehow?

**Comment by alekcac** [comment]
I will investigate it. I am not sure that it is auto generated. So if you can reproduce it, it will be useful.

**Comment by StevenPuttemans** [comment]
This was the last one:
-----------------------------
OpenCV answers feedback

EmeryYocum (nildabrandenburg@hotmail.com, ip:64.120.61.129) wrote:

Attractive section of content. I just stumbled upon your weblog and in accession capital to assert that I get actually enjoyed account your blog posts. Any way I will be subscribing to your augment and even I achievement you access consistently fast.

Sincerely,
OpenCV answers Administrator

**Comment by StevenPuttemans** [comment]
I am just wondering if someone would actually use that interface to communicate ...

**Comment by alekcac** [comment]
I have changed settings, now you should be authorised user to send feedback, maybe it changes the situation.

**Comment by StevenPuttemans** [comment]
:+1:

**Comment by StevenPuttemans** [comment]
It is not working. Have not had any authorization request and have received more than 15 mails starting last night. Lets remove the feedback option?

**Comment by alekcac** [comment]
Yes, it doesn't work. I removed feedback form from the site.

**Comment by alekcac** [comment]
I thought a bit more and returned link for feedback. But it goes to this issue tracker now. Let's try to test this scheme.

**Comment by StevenPuttemans** [comment]
:+1:
