### ISSUE TITLE
New ways to stop spam

### ISSUE THREAD

**Issue by alekcac** [opencv-infrastructure/answers.opencv.org#14]

**Comment by StevenPuttemans** [comment]
It seems that even tough we have a moderation queue, I delete about 25-50 spam messages/accounts daily using that queue.

Positive
- It does not get into the forum itself
- People are not aware of it any more

Downside
- Moderators have extra work cleaning it (@berak can confirm this)
- It is frustrating to see

I am wondering what would be ideal to get this flood fill stopped. How hard would it be to integrate for example the new recaptcha software from google (https://www.google.com/recaptcha/intro/index.html) into posts for lets say, users with karma lower then 35 and make sure that it does not get into the queue before they click it? I guess this would solve it all!

**Comment by berak** [comment]
![clipboard01](https://cloud.githubusercontent.com/assets/854416/11766431/9b89dd6a-a187-11e5-9eb6-7c53c91c9bf2.png)

**Comment by StevenPuttemans** [comment]
Jup aware of same problem. And thing is, by bunch deleting them you also block out new users so we need to go through 1 by 1....

**Comment by berak** [comment]
this thing is awesome: https://app.monkeylearn.com/categorizer/projects/cl_rsfuc4Ji/tab/test-tab

**Comment by StevenPuttemans** [comment]
Since spam has been at a all time low point since the past year, I guess this can be closed down?

**Comment by sturkmen72** [comment]
is it possible to activate captcha system
see https://answers.ros.org/questions/ask/

**Comment by StevenPuttemans** [comment]
@sturkmen72 thats the plan, but for that we first need an update of the actual back-end software, which @mshabunin is planning in the future.

**Comment by mshabunin** [comment]
The forum software has been upgraded to Askbot 0.10.2 with ReCaptcha 2 and Akismet integration enabled.
