### ISSUE TITLE
Missing *convert to answer* option

### ISSUE THREAD

**Issue by LorenaGdL** [opencv-infrastructure/answers.opencv.org#16]
I've might have spotted another changed caused by the upgrade. Before, there was a nice _convert to answer_ option when hovering the mouse over one's comment. Now it's gone, and I found it pretty nice and useful. I think moderators still have the option to convert comments into answers, but I'd rather not bother them with such issue (they're too busy cleaning spam...)

Any possibilities to bring such function back?

**Comment by StevenPuttemans** [comment]
The option is still there for moderate users :D just ping me, will be the easiest way. I try to make answers as much as possible!

**Comment by StevenPuttemans** [comment]
@alekcac is the current setting that moderators only get access to this function? If so, can we make it more general or give @LorenaGdL moderator right for being quite active on the forum?

**Comment by mshabunin** [comment]
Not an issue anymore.
