### ISSUE TITLE
repeated downvote bug

### ISSUE THREAD

**Issue by berak** [opencv-infrastructure/answers.opencv.org#17]
- 1st downvote removes a vote, and removes 10 karma points from poster
- 2nd downvote resets the prev. downvote, but still removes 10 more karma points from poster
- 3rd downvote removes a vote, and again removes 10 more karma points from poster.
- ... ad libitum

(i don't mind the karma, tbh, it's more a favour, still a bug)

**Comment by StevenPuttemans** [comment]
... and we should mention that some person with way to much time has abused this to downvote about 3k karma of @berak! :D

**Comment by StevenPuttemans** [comment]
I tought that @alekcac got this fixed?
