### ISSUE TITLE
Spam not yet gone - what else can we do?

### ISSUE THREAD

**Issue by StevenPuttemans** [opencv-infrastructure/answers.opencv.org#2]
I am seeing that there is still a set of spammers getting through. Deleting 1-2 spammers at least each day. Okay premoderation makes sure they can only spam once but we should increase security as suggested.

Remark from @berak
unfortunately, though there is a captcha for signup, still no e-mail validation

**Comment by alekcac** [comment]
We can add email validation but I should test it before because this feature is not very stable.

**Comment by StevenPuttemans** [comment]
I agree, email validation would be a good improvement. 
Is there any other manner of checking if a registered user is a spammer or not?

**Comment by berak** [comment]
if someone gets bored ...

http://answers.opencv.org/users/?t=user&query=sports&search=
http://answers.opencv.org/users/?t=user&query=green&search=

school, exam, cart, holiday, 

we got the whole yellow pages here ;)

**Comment by StevenPuttemans** [comment]
Oh man :D this should be deleted from database level based on like a rubbish bio?

**Comment by berak** [comment]
maybe we should better watch the backdoor, anyone with a flag is spam.

![clipboard02](https://cloud.githubusercontent.com/assets/854416/10359204/8f87ed88-6d96-11e5-9041-a9ba2a0e7cfb.png)

**Comment by StevenPuttemans** [comment]
@berak that is because they still have not posted their first post. From the moment they do that, we get a notice and they get deleted and blocked. However the registration is still open for bots. Maybe we should do a database clean based on all accounts with 0 posts? @alekcac what do you think?

**Comment by berak** [comment]
still, the profiles contain spam links, that will be referenced from other diluted forums, which again causes unwanted traffic at opencv's cost.

more moderators, cleaning up, now & then, maybe.

**Comment by alekcac** [comment]
Thanks for the report! I will analyse possible steps and will return here after this activity.

**Comment by StevenPuttemans** [comment]
@berak true true :)
@alekcac thanks

**Comment by StevenPuttemans** [comment]
Maybe interesting: http://askbot.org/en/question/13484/how-do-you-enable-captcha-on-the-login-page/
It seems to be possible to enable CAPTCHA when registrating on the site.
