### ISSUE TITLE
forum is (suddenly) slow

### ISSUE THREAD

**Issue by berak** [opencv-infrastructure/answers.opencv.org#22]
request to main page takes more than 2 minutes (since about 28.4).

see also [here](http://answers.opencv.org/question/94042/forum-is-very-slow/)

**Comment by berak** [comment]
website is down completely, now.

**Comment by PkLab** [comment]
Website is down again. Is there any news ?

**Comment by StevenPuttemans** [comment]
It is still down :) as far as I see it, it will be either due to updates on the server end, or the thing breaking down completely. @alekcac got any clue what is going on?

**Comment by TheodoreT** [comment]
it seems that they are changing template or something, at some point I managed to open it a couple of minutes ago and the template of the forum seemed a bit different. However, now I cannot connect to it again.

**Comment by LorenaGdL** [comment]
@TheodoreT if you saw a black&white tempalte, I'm sorry to say that they're not changing a thing. I've seen that template quite a few times before when my connection is slow, and the forum does not load properly. I guess it's just the basic template or something.

**Comment by TheodoreT** [comment]
Ok, that could be the case :-(. That's bad, though... Anyways, we live to hope for changes :-p...

**Comment by mshabunin** [comment]
There seems to be a problem with the hosting, code.opencv.org and answers.opencv.org are not working. We are trying to figure out the cause of the problem.

**Comment by StevenPuttemans** [comment]
:+1:

**Comment by alekcac** [comment]
Hi Steven,

I am in vacation now and I was offline last week. We have some issues with current hosting. In my opinion one of HDDs in our server has hardware issue. We are trying to find the reason of such behavior with hosting support. We will try to fix issues with website as soon as possible.

Alex

**Comment by StevenPuttemans** [comment]
No problem Alex! We will hear it when it is fixed!

**Comment by TheodoreT** [comment]
@alekcac is it that bad the problem?

**Comment by alekcac** [comment]
Both hard disks in the server that hosted answers.opencv.org and code.opencv.org are failed. So they will be changed to the new ones by hosting company and then we will restore the both websites. I think we should finish at the end of this week.

**Comment by TheodoreT** [comment]
great, sounds good :+1:

**Comment by alekcac** [comment]
I added chat room for this repository. If you have some questions or ideas and you don't want to create new issue, feel free to use it. Only one rule: we discuss only answers.opencv.org website, not OpenCV.

**Comment by ttsesm** [comment]
Hi @alekcac, may I ask where did you add this chat room? Also another thing, that many active users (most appearing in this discussion) was if there is the possibility to change/improve the form of the answers.opencv.org website. My personal opinion, and of some others is that the website is lacking some functionalities. Due to the growth of the library and of the users since the last years the form of the website I would say that is quite limited.

**Comment by alekcac** [comment]
Hello, you can find the link on the main page of the repo: https://github.com/opencv-infrastructure/answers.opencv.org. If you want to continue discussion please use chat room, this issue is about our issue with hosting.

**Comment by ttsesm** [comment]
perfect :+1: 
thanks!  ;-)

**Comment by LorenaGdL** [comment]
Seems it's up again :)

**Comment by berak** [comment]
thanks for fixing it !

**Comment by RoyiAvital** [comment]
By the way, it still seems that the OpenID log in using Yahoo ID doesn't work.
Though it works on StackExchange sites.

Thank You.
