### ISSUE TITLE
"pre-check" answers on the moderation page

### ISSUE THREAD

**Issue by berak** [opencv-infrastructure/answers.opencv.org#25]
@alalek , is there any chance to have those checkboxes on the moderation page checked " by default" ?

it would definitely ease the work on moderation here, since you only would have to "uncheck" the legit posts (rare species, unfortunately), and send the remaining ~50 ones to hell using the red button in one go.

(~300 bad ones last weekend, imagine fiddling with 3mm boxes on a laptop trackpad)

(locally, i solved it by adding some jsinjector add-on to my browser, and adding some script to check any "checkbox" input, but it would be far easier, if that would be the default.)

**Comment by mshabunin** [comment]
@berak , was it fixed?

**Comment by berak** [comment]
@mshabunin not really, after meeting some folks, who got misclassified for spam, i rather thought, it might not be the best idea.
