### ISSUE TITLE
Report account blocked issue with no reason.

### ISSUE THREAD

**Issue by GoldenWings** [opencv-infrastructure/answers.opencv.org#26]
Hi,
I've just created my account today and asked a question about haar classifier.

And i've just logged in 10 minutes ago to check if there are any answers to my question to found a message telling me my account is blocked and it might be an error please contact administrator.

Username: GoldenWings
Email: mohamedalzaki@outlook.com

Any help please?

**Comment by berak** [comment]
apologies, site had to go moderated due to a lot of spam, and you somehow ended up in the wrong queue. this was for sure an error, but bare with us, we're all humans.

can you try again ? (you'll probably have to use another nick, but email is not blocked at all)

**Comment by GoldenWings** [comment]
Its ok, and i feel you guys spams kills hope u stop it all some how.

You mean i create new account? if so sure i can do so.

**Comment by berak** [comment]
sure, please do so ! (just go to the sign-on page, and try with a new nick (same email, it's never checked)

**Comment by GoldenWings** [comment]
Done but with other email, please approve my question and if you could help that would be a great gift :)
http://answers.opencv.org/question/108599/haar-classifier-limitations/

Thanks

**Comment by berak** [comment]
approved, and apologies for the incident again.
