### ISSUE TITLE
Cannot access my OpenCV account

### ISSUE THREAD

**Issue by hilmandayo** [opencv-infrastructure/answers.opencv.org#27]
Hi everyone. I have a problem. Turns out, I cannot access my account. It says I got blocked. I don't know why. When I click my name (at top right of the page), I get this:

<img width="1203" alt="screen shot 2016-12-26 at 11 09 34 am" src="https://cloud.githubusercontent.com/assets/16521877/21473940/dd92594a-cb5b-11e6-9ed4-a23a00c57615.png">

Why is this? The last question that I have post, and for some reasons got deleted is [this](http://answers.opencv.org/question/120184/how-to-construct-3d-representation-of-the-scene-with-more-than-2-images/).

**Comment by berak** [comment]
dearest apologies for that mishap.
site is under spam attack, and had to go moderated, somehow you got into the wrong queue, it's a simple, human error.

the good new is, given the link to your last question, i could restore your account and questions,
so i hope, everything is ok, now.
again sorry, that it happened, bear with us, we're all only humans there

**Comment by hilmandayo** [comment]
Thanks!
