### ISSUE TITLE
Forum is slow again

### ISSUE THREAD

**Issue by LaurentBerger** [opencv-infrastructure/answers.opencv.org#28]
Hi,
I think forum latency is too high again. Sometime I can wait 30 seconds to refresh page and 5 minutes later everything is fine. but most of the time it is slow I can say that's not a Wysiwyg forum. Is it possible to investigate where is the problem?

Thanks

**Comment by PkLab** [comment]
Similar to me. Can we do any test on client side ? For example, at this time 
```
ping -n 100 answers.opencv.org
    0% Lost     Min = 44ms, Max =  145ms, Avg =  86ms
```
browsing answers.opencv.org/questions/  browser (Firefox Developer) network inspector says
```
19.7 s GET /questions/
22.9 s GET /jsi18n/
31.7 s GET sprites.png with Error 404 !
```

browsing /question/12979...  inspector says
```
34.5 s GET /question/12979...
24.8 s GET /jsi18n/
20.8 s GET sprites.png with Error 404 !
```

Second test few seconds later shows same ping time but loading times are reduced to 5s in total either home or question (off course the browser cache is off)

**Comment by LaurentBerger** [comment]
10.9 s GET /questions/
6.98 s GET /jsi18n/
6.7 s GET custom.css?v=6
4.7 s GET sprites.png with Error 404 !

if you try on this forum http://askbot.org/en/questions/
0.378 s GET sprites.png  and it is http://askbot.org/m/default/media/images/sprites.png?415283abcfa2

When lattency is slow (1.4s) there is still an error 404 wit 0.285s

**Comment by mshabunin** [comment]
Not sure if it was the root cause of this concrete problem, but some time ago I've tuned some database parameters and site become faster. For now I get 1.3-1.7 s for full `/questions/` page load.
