### ISSUE TITLE
Must we cite the author name code in a post ?

### ISSUE THREAD

**Issue by LaurentBerger** [opencv-infrastructure/answers.opencv.org#29]
Hi,

In this post http://answers.opencv.org/question/135811 it seems that orignal code is http://cs-people.bu.edu/leenshe/CS440_A1/. Is it fair to forget author name of this code in the post?

**Comment by berak** [comment]
do you really think, that person is reading cs websites ? code looks more like copypasted from one blog to the next (also, losing some bits each time, heh)

**Comment by LaurentBerger** [comment]
Original code is too strong Ok. But write in post "that's not my own code I found it here " it is better than nothing.
