### ISSUE TITLE
accidentally blocked posts, how to undo ?

### ISSUE THREAD

**Issue by berak** [opencv-infrastructure/answers.opencv.org#33]
damn, it happened. i just blocked 3 valid posts/users.

i could retrieve the revisions, but the names are lost, so i can't undo it. any idea, what to do ?

http://answers.opencv.org/questions/145966/revisions/
http://answers.opencv.org/questions/145970/revisions/
http://answers.opencv.org/questions/145972/revisions/

how did [this previous incident](https://github.com/opencv-infrastructure/answers.opencv.org/issues/30) get resolved ?

**Comment by StevenPuttemans** [comment]
Actually the names we trying to restore are: Lavanya, Kiran93, mlanus. In the past, you could look up the names and see them as blocked users, but it seems that is no longer the case. Possible their account gets deleted from repository now?

**Comment by berak** [comment]
how did you find the names?

**Comment by StevenPuttemans** [comment]
> how did you find the names?

By going to the revisions and hitting the edit button on top :) I will see if somehow I can restore the posts this way...

**Comment by StevenPuttemans** [comment]
Editing and saving content to restore is no longer possible, since content is deleted. Probably some conflict somehow.

**Comment by berak** [comment]
blocked users are still in the db, [example](http://answers.opencv.org/users/117093/russmaiden/)

if i only had the user id for those names, i could undo it

**Comment by LaurentBerger** [comment]
I have block my testuser and account is not in database now

**Comment by berak** [comment]
@LauentBerger, `http://answers.opencv.org/users/<ID>/<NAME>`  

(unfortunately, it needs both name & id to get there)

**Comment by berak** [comment]
i seem to have a knack for pressing the wrong button today, sorry.

**Comment by mshabunin** [comment]
Ok, I've unblocked all three users:
http://answers.opencv.org/users/117339/lavanya/
http://answers.opencv.org/users/117356/kiran93/
http://answers.opencv.org/users/117347/mlanus/
Will try to restore questions...

**Comment by LaurentBerger** [comment]
new account is _**testuser2**_ with a post in moderation list.  I think if you select and block user account cannot be found in search button but it is still present in askbot because @mshabunin is able to find it.  email of my first test is blocked (user **testuser** ) May be difference is badge autobiographer

**Comment by mshabunin** [comment]
Probably it can not be found because user search and sorting does not work in this Askbot version :cry: 
Blocked accounts and posts are still in database.

**Comment by berak** [comment]
well, @mshabunin was faster (thanks a ton, again !), but, just for the record i found a way to find the user ids using the [askbot api](https://askbot.org/doc/api.html)

    for /L %u in (1,1,100) do curl "http://answers.opencv.org/api/v1/users/?sort=recent&page=%u" >> users2.txt

(well, that retrieves the last 100 pages)

if we have name and id, we can go to [the moderation page](http://answers.opencv.org/users/117356/kiran93/) and unblock.

**Comment by mshabunin** [comment]
I've reasked questions on behalf of users, but I accidentally broke question http://answers.opencv.org/questions/145972/revisions/ (by merging it with itself)  and can not find it.
If you have copy of the question, please post here, or we should ask user to ask it again via direct message or e-mail.

**Comment by berak** [comment]
i sent an apology e-mail (via moderation page) , asking to re-post.

again, thanks a lot for all your help with this !

**Comment by StevenPuttemans** [comment]
@berak @mshabunin I suggest to make a wiki page on fixing commands like the one suggested by @berak, so that we can keep useful things like that together without having to roam open/closed issues.

**Comment by StevenPuttemans** [comment]
Can you guys unlock dkurt? It seems he tot locked out.

**Comment by LaurentBerger** [comment]
dkurt not found between "joined_at": "1495655469", "id": 135893} and "joined_at": "1494428653", "id": 123201} but i found Kurt99K50 KurtCompto NellKurtz

**Comment by dkurt** [comment]
Hi all! Probably, I have one more account and I'll use it.
If it can help you, before I was blocked I have pressed "More" -> "Repost as a question comment" on my one and only account answer. It already has one comment from topic starter. So after it I've seen the same question with two comments: my last answer and user respond. Then I've tried to add one more comment and when it was queued to moderation I was blocked after some time.
Thank you for help!

**Comment by berak** [comment]
@dkurt, don't close any tabs ! if you can retrieve the user id, we can simply unblock it !

is [this](http://answers.opencv.org/users/64037/dkurtaev/) your other account ?

**Comment by mshabunin** [comment]
Or this: http://answers.opencv.org/users/21507/dmitry-kurtaev ?

**Comment by mshabunin** [comment]
Ok, I've found and unblocked: http://answers.opencv.org/users/132589/dkurt/

Looks like blocked users are not listed in the users list and can not be retrieved via Askbot API.

**Comment by LaurentBerger** [comment]
@mshabunin In my list (using api as suggested by @berak)  : "id": 132591 "id": 132590 "id": 132588...no 132589 I haven't got id  132583  132582 ....

**Comment by berak** [comment]
http://answers.opencv.org/api/v1/users/132589/
http://answers.opencv.org/api/v1/users/132583/
http://answers.opencv.org/api/v1/users/132582/

so, they're all there, but you can't get to those via http://answers.opencv.org/api/v1/users/?sort=recent&page=XXX

unfortunately, say, a day later, we're already at userid 137771 (that's like +1000 in 24 hrs) so manually scanning the users does no more seem feasible at all ;(

**Comment by dkurt** [comment]
Thank you guys!

**Comment by StevenPuttemans** [comment]
Guys can you take a look at this guys blocked account: https://github.com/opencv-infrastructure/answers.opencv.org/issues/35
