### ISSUE TITLE
Account Blocked

### ISSUE THREAD

**Issue by yeg679** [opencv-infrastructure/answers.opencv.org#35]
My account has been blocked on answers.opencv.org and I have no idea why. I signed up to ask a question about detecting and capturing a custom 2D marker, but haven't seen my question or been able to ask another since then.

As far as feedback goes:
- Attempting to ask a question shows that my account is blocked
- Clicking on my username takes me to a Page Not Found page
- Clicking the 'report this problem' link on the Page Not Found page takes me to the same Page Not Found page
- Searching for the question I asked shows nothing
- I sent an email to admin@opencv.org, but have not received a reply

**Comment by mshabunin** [comment]
Is this your account: http://answers.opencv.org/users/185982/transfinite-sorcerer ?
