### ISSUE TITLE
New User Account blocked

### ISSUE THREAD

**Issue by kunal423** [opencv-infrastructure/answers.opencv.org#36]
Hi everyone,

I recently created an account with username **kunal10** and asked question titled `how to use cv2.omnidir.calibrate()` and commented on [this question](http://answers.opencv.org/question/143514/fisheye-distortion-correction-using-omnidir-namespace-change-of-perspective/) as I am also seeking advice on same thing.

After I posted my question it said that waiting for moderator approval, today when I logged in to my account it was blocked :'( 

I hope this is resolved soon.

**Comment by LaurentBerger** [comment]
dearest apologies for that mishap. Your account is unblocked. I don't know how to restore your comment and question

**Comment by kunal423** [comment]
@LaurentBerger So should I repost the question ?

**Comment by LaurentBerger** [comment]
yes sorry as moderator I cannot  restore your question and comment. Only administrator site can do it. If you want him to restore your question, ask to admin in this issue or just repost your question.

**Comment by kunal423** [comment]
@LaurentBerger I don't know who is the admin. Can you tag the appropriate person on this issue to restore this question - **http://answers.opencv.org/question/159576/how-to-use-cv2omnidircalibrate/**

**Comment by LaurentBerger** [comment]
@kunal423 he is already watching this issue https://github.com/opencv-infrastructure/answers.opencv.org/watchers  @mshabunin

**Comment by mshabunin** [comment]
@kunal423 , could you please post your question again. As I see, the comment has been restored automatically.
