### ISSUE TITLE
Add the AskBot details like version running and such to the README.m file

### ISSUE THREAD

**Issue by StevenPuttemans** [opencv-infrastructure/answers.opencv.org#4]
It would be good if admins and others could have all the AskBot server version details in the README. Could be good for mentioning when posting at the Askbot forum.

**Comment by alekcac** [comment]
What do you mean? Could you add more details?

**Comment by StevenPuttemans** [comment]
I need to clone this repo if I want to adapt this file (https://github.com/opencv-infrastructure/answers.opencv.org/blob/master/README.md)

I would like to add details like 
AskBot version = 0.7.50 

And any others that are interesting for bringing along to the AskBot forum when digging deeper!
