### ISSUE TITLE
Page not found when clicking on account

### ISSUE THREAD

**Issue by davidparks21** [opencv-infrastructure/answers.opencv.org#40]
When I try to click on my account, I get a page not found here (image below). 

I also can't post questions/vote/etc. It says my account is disabled and I should contact an administrator.

From my view there are a number of broken links on key pages.

![image](https://user-images.githubusercontent.com/964997/28535024-c45de57e-7057-11e7-9e0b-a20210e7f9c4.png)

**Comment by berak** [comment]
so apologies, if that happened.

cool thing is: your screenshot has both user id and username, so easy for me to correct the mishap.

(please understand, there's a lot of spam posts to our site, it had to go"moderated", and now, & then, human errors occur at that point)

**Comment by mshabunin** [comment]
The issue has been resolved.
