### ISSUE TITLE
Account blocked

### ISSUE THREAD

**Issue by burhanbvk** [opencv-infrastructure/answers.opencv.org#42]
When I login I see a "sorry your account is blocked" message, telling me to contact the site administrator. But I don't see any contact options on the answers site.

**Comment by berak** [comment]
oh , apologies, if that happened, human error, and this is the perfect place to ask. 

(most probably, your post got misclassified between a ton of spam.)

do you happen to remember your user id ? (else we need someone with database access)

**Comment by burhanbvk** [comment]
Thanks! My user id is 363565.

**Comment by berak** [comment]
oh, cool ! (people rarely remember *that*)

i was able to restore [your account](http://answers.opencv.org/users/363565/burhan986/), unfortunately, whatever question you had, -- you'll have to ask anew.

again, sorry for the mishap, and best of luck !

**Comment by burhanbvk** [comment]
Thanks a lot. I guess the same goes for the answers I gave? 

I wonder if there were any issues with my answer itself (to this question here http://answers.opencv.org/question/171021/best-programming-language-for-development/). At the end of my answer I said that I would be interested in collaborating. Is that considered as spam?

**Comment by berak** [comment]
no, don't worry, there's a red and a blue button, and it's just easy to hit the wrong one (for me, too !), given ~100 posts a day.

however, sadly your answer is gone. can you try to write it again ?

**Comment by burhanbvk** [comment]
Got it, thanks again.
