### ISSUE TITLE
Blocked account

### ISSUE THREAD

**Issue by ronejercito** [opencv-infrastructure/answers.opencv.org#43]
Hi,

I'm not sure where I'm supposed to go. I just signed up for an account in answers.opencv.org. I posted a question and then my account got blocked. I don't know how to access the administrators.

**Comment by mshabunin** [comment]
@ronejercito , what is your username and id?

**Comment by ronejercito** [comment]
Hi Sir,

My username is Toast_Brew but I don’t remember my id.

Ron

**Comment by mshabunin** [comment]
I've restored your account, probably it have been blocked by mistake, sorry for inconvenience. Unfortunately I can not restore your question so you should post it again.
