### ISSUE TITLE
Down-voting system

### ISSUE THREAD

**Issue by eshirima** [opencv-infrastructure/answers.opencv.org#44]
I was just curious on what criteria was used in deciding the amount of points deducted from a question down-vote.

I posted a question a day ago and had an accidental downvote. To my surprise, 10 points were deducted and that left me with just 21 karma points. By comparison, [SO](https://stackoverflow.com/help/privileges/vote-down) doesn't impose a penalty on question down votes.

I appreciate the amount of time you guys are putting into moderating the site as a whole and if having a karma reduction for question down vote helps in discouraging spam questions, I am all for it. But a 10 point reduction is REALLY on the steep side especially for first timers. A 2-5 point reduction sounds fair.

**Comment by berak** [comment]
yea, that part is slightly broken.

if you downvote a question (or answer), 10 points are subtracted from your karma, but they're not re-added, if the operation is revoked (by clicking it again), only the "answer score" is repaired.

**Comment by berak** [comment]
it's simply a bug in the askbot software

**Comment by sturkmen72** [comment]
@mshabunin 
on moderation setting page

"Karma loss and gain rules" >> "Loss for owner of post that was downvoted " setting it to 2 will solve this problem

or set "Gain for post owner on canceled downvote" to 10

i prefer first solution

**Comment by mshabunin** [comment]
@sturkmen72 , let's try it.
![image](https://user-images.githubusercontent.com/3304494/29248269-93293f60-801c-11e7-894f-6be5b9cc1f8c.png)

**Comment by berak** [comment]
that seems to solve it for me. (thanks !)

**Comment by sturkmen72** [comment]
@mshabunin thanks... i believe i will be more helpful if i have moderator rights

**Comment by StevenPuttemans** [comment]
Adding an extra moderator can never hurt I guess ^_^
@eshirima can you close this down?

**Comment by eshirima** [comment]
Thanks guys for the clarification.
