### ISSUE TITLE
what about deleting useless posts?

### ISSUE THREAD

**Issue by sturkmen72** [opencv-infrastructure/answers.opencv.org#45]
hi,
As highlighted in previous discussions. there are many useless posts in forum ( duplicates , off-topic subjects etc.)

i already retagged some of them as [deleted](http://answers.opencv.org/questions/scope:all/sort:activity-desc/tags:deleted/page:1/) and will keep doing so.

maybe we will decide together on what kind of questions can be deleted completely.

i tagged some questions to became a sample for a group

1. [deleted-lost-user](http://answers.opencv.org/questions/scope:all/sort:activity-desc/tags:deleted-lost-user/page:1/) this questions are asked by a user who never log in again. maybe some of them seems a valid question but because they have no answer

2. [deleted-duplicate](http://answers.opencv.org/questions/scope:all/sort:activity-desc/tags:deleted-duplicate/page:1/) obviously no need to keep this questions while duplicate of them available

3. low quality unanswered old questions like http://answers.opencv.org/question/29391/how-i-set-canny-image-to-region-of-interest-using-open-cv/

4. [already closed for the following reason "not a real question"](http://answers.opencv.org/question/9757/need-help-debugging/)
5. [questions answered by addressing to a previous answer](http://answers.opencv.org/question/69035/tickmeter-class-removal-and-how-to-replace-it/)
6. [off-topic](http://answers.opencv.org/questions/scope:all/sort:activity-desc/tags:off-topic/page:1/)
.
.
. etc.

what is your opinion about this idea

**Comment by StevenPuttemans** [comment]
Hi @sturkmen72 , I agree that a clean-up could be done on existing topics. Especially since older topics contain a lot of C-style solutions. I do like the fact you are adding tags, but isn't that just a crazy ass amount of work?

The not a real question ones, I already systematically simply delete them.

**Comment by StevenPuttemans** [comment]
But I guess there must be an automated way of retrieving all closed questions and systematically delete them?

**Comment by berak** [comment]
hi, @sturkmen, i agree on all your 6 points above.

so, you're basically adding a "proposal for future deletion" there ? what should happen then ?

(btw, we can only delete the link, not the db item)

**Comment by StevenPuttemans** [comment]
> (btw, we can only delete the link, not the db item)

Wait if we delete something it still clogs up the database?

**Comment by sturkmen72** [comment]
yes deleted posts remains in the db
i opened i trial [askbot](http://sturkmen72.askbot.com)
anyone can log in as administrator using 
Login or email : sturkmen72
Password : opencv33

**Comment by sturkmen72** [comment]
i looked [askbot management-commands ](https://askbot.org/doc/management-commands.html)
maybe @mshabunin will try some of them like "delete_unused_tags" "rename_tags"
also i will try to find a way for manipulating database.

**Comment by mshabunin** [comment]
Deleting questions is quite complicated process, there is no existing mechanism for doing this and I don't know askbot database architecture well enough.

@sturkmen72 , not sure which tags should be renamed?

**Comment by sturkmen72** [comment]
related forum post https://answers.opencv.org/question/235390
