### ISSUE TITLE
Colour Schema

### ISSUE THREAD

**Issue by eshirima** [opencv-infrastructure/answers.opencv.org#46]
After the maintenance, the forum's colour schema is different.
It's less user-friendly and not consistent. The background colour when the mouse is hovered over the menu is just daunting.

[Image 1](http://imgur.com/a/zdjtD)
[Image 2](http://imgur.com/a/bBYbf)
[Image 3](http://imgur.com/a/U5yEX)

Please change this. I beg of you. Pity please 😭 

**UPDATE**
Profile pics too are missing

**Comment by mshabunin** [comment]
@eshirima , thank you! I've fixed CSS and avatar mode. Feel free to reopen if you observe more similar issues.
