### ISSUE TITLE
Unable to change to my answer

### ISSUE THREAD

**Issue by LaurentBerger** [opencv-infrastructure/answers.opencv.org#47]
@mshabunin and opencv team : 👍 Thanks for new forum.

I have got a problem when I want to modify my answer example [this one](http://answers.opencv.org/question/173057/display-a-text-on-the-windows-with-opencv-and-c/)
1 I press edit and add"something in source code"
2 I can see my modification in preview
3 press save button 
4 I can see my new answer 
5 after one minute I update page and I still have my old answer. 

Can you reproduce this issue ? Or I 'm doing something wrong?

**Comment by LaurentBerger** [comment]
I changed computer it's ok ... problem is solved

**Comment by berak** [comment]
@LaurentBerger , i've seen something like this, too !

**Comment by LaurentBerger** [comment]
@berak problem is in my fiirefox 
 Forbidden (403)

CSRF verification failed. Request aborted.

More information is available with DEBUG=True

**Comment by mshabunin** [comment]
I restarted the server around this time, it could be the root cause. Please let me know if the problem persists.

**Comment by LaurentBerger** [comment]
thanks @mshabunin Problem persists but I think my firefox config is wrong. Using Edge on same computer everything is fine.

**Comment by LaurentBerger** [comment]
Problem is solved : I deleted all answers.opencv.org cookies.
