### ISSUE TITLE
about karma change log

### ISSUE THREAD

**Issue by sturkmen72** [opencv-infrastructure/answers.opencv.org#48]
in my opinion it is not a serious problem but just wanted to report.

karma change log doesn't work as like before.
before update it was listing all changes in date order.

for example see [mine](http://answers.opencv.org/users/16589/sturkmen/?sort=reputation)

**Comment by LaurentBerger** [comment]
Where is faq button?

**Comment by mshabunin** [comment]
@sturkmen72 , I will take a look and try to fix the order.
@LaurentBerger , there is a link in the footer, I don't remember where else it was.

**Comment by sturkmen72** [comment]
i get frequently "Internal server error"

for example:
 [stevenputtemans's profile](http://answers.opencv.org/users/681/stevenputtemans/)
[berak's profile](http://answers.opencv.org/users/2130/berak/) getting "Internal server error"

[LBerger's profile](http://answers.opencv.org/users/8129/lberger/) working

**Comment by LaurentBerger** [comment]
It was : http://web.archive.org/web/20170109091814/http://answers.opencv.org/questions/

**Comment by StevenPuttemans** [comment]
@sturkmen72, I already reported it to @mshabunin and it seems it is due too the fact that the new askbot system cannot handle medals and posts that were in the old system but which are no longer supperted in the new system. Therefore @mshabunin will try to reload all medals on top of the new database and check if these issues disappear this way.

**Comment by StevenPuttemans** [comment]
@mshabunin FAQ button was at the top right, as an exta colored block next to users and so on.

**Comment by berak** [comment]
in the bottom line, it says:

> Copyright Itseez, 2012-2016. Content on this site is licensed under a Creative Commons Attribution Share Alike 3.0 license.

i guess, that needs an update, too ;)

**Comment by StevenPuttemans** [comment]
> @sturkmen72, I already reported it to @mshabunin and it seems it is due too the fact that the new askbot system cannot handle medals and posts that were in the old system but which are no longer supperted in the new system. Therefore @mshabunin will try to reload all medals on top of the new database and check if these issues disappear this way.

Actually it seems this is fixed now. I can access my profile just fine: http://answers.opencv.org/users/681/stevenputtemans/

**Comment by StevenPuttemans** [comment]
Since we keep reporting btw, found another bug in the software

![image](https://user-images.githubusercontent.com/4621239/29861803-d491d18c-8d6a-11e7-97d2-65bba6048f7a.png)

If your username is to long, the flag drops a level and thus the achievements cannot be seen anymore in the overview. Not a big issue I guess, but worth mentioning.
