### ISSUE TITLE
Cannot add tags

### ISSUE THREAD

**Issue by parzival2** [opencv-infrastructure/answers.opencv.org#49]
It complains when i m trying to add tags, i have tried all the possible ways to add tags. If i put `#` infront, it complains that # sign is not an accepted character. 
I have been trying to ask a question and its not letting me to.

**Comment by LaurentBerger** [comment]
Hi, sorry for inconvenience. What's your username on answers.opencv.org.

**Comment by parzival2** [comment]
Hi, Thank you for the quick reply, 
i will be under "the_parzival".

**Comment by LaurentBerger** [comment]
I cannot see any problem on [your account](http://answers.opencv.org/users/397751/the_parzival/?sort=stats). please try again

**Comment by sturkmen72** [comment]
@parzival2 please try to use tag "2011" (it is just a simple one to be sure is there a problem really)

**Comment by parzival2** [comment]
@sturkmen72 Just tried that, its giving the below information on the page.
As soon as i type `opencv` its giving a list of options starting with #. When i select one, suppose `#opencv`, and press `ask question`. It says that # is not a valid character.
`Internal server error
system error log is recorded, error will be fixed as soon as possible
please report the error to the site administrators`

**Comment by LaurentBerger** [comment]
Just try [without # It works ](http://answers.opencv.org/question/173249/test-tag-sdkdksdjsd/)use tag opencv only you can retag your question latter

**Comment by sturkmen72** [comment]
"As soon as i type opencv"

just type "2011" and press Enter

**Comment by parzival2** [comment]
@sturkmen72 @LaurentBerger Did that its giving me 
`Internal server error
system error log is recorded, error will be fixed as soon as possible
please report the error to the site administrators` 
this error.

**Comment by sturkmen72** [comment]
ok. lets wait for a while.

you can ask your question here. i will post it.

**Comment by LaurentBerger** [comment]
can you post a screen copy in your post (drag and drop image) just before error ?

**Comment by parzival2** [comment]
@LaurentBerger Below you can find the images i have screen shot while i got error and before pressing ask question button.
![before_ask_question](https://user-images.githubusercontent.com/22563463/29893721-489ac6ca-8dd3-11e7-9449-8564dac9eb38.JPG)
![error_screen](https://user-images.githubusercontent.com/22563463/29893722-48b17500-8dd3-11e7-962a-7d32468ef993.JPG)

**Comment by parzival2** [comment]
@sturkmen72 Thank you, Here is the question i wanted to ask.
**Question :** 
 I am trying to calibrate a stereo setup consisiting of two identical Canon EOS60D's, which i will be using to do Photogrammetry. To calibrate cameras i am using a high precision circlegrid pattern plate. I was able to detect centre points of circles using `cv2.findCirclesGrid`, and was able to calibrate a single camera just fine. The problem comes when i try to calibrate both cameras using `cv2.stereoCalibrate` function in OpenCV. I will elucidate the steps taken and also post some code snippets with outputs i have got. I would be grateful if someone can point out where i am doing wrong.

**Steps**

1) First step is to detect circlegrid pattern using `cv2.findCirclesGrid` function in OpenCV.

2) Then using the detected grid pattern from each camera, i am using `cv2.calibrateCamera` to get camera matrices, and distortion coefficients of both cameras.

3) After getting camera matrices and distortion coefficients of both cameras, i am passing them to `cv2.stereoCalibrate` function.

**Output**

output after calibrating Left Camera is as follows

    Left Camera Return Value :  0.202690712694
    Left Camera Camera Matrix :  [[  2.42046647e+04   0.00000000e+00       1.78281995e+03]
    [  0.00000000e+00   2.42115121e+04   2.51720578e+03]
    [  0.00000000e+00   0.00000000e+00   1.00000000e+00]]
    Left Camera Dist Coeff :  [[-0.09448288 -1.38934436  0.00951455 -0.00568115  0.11248399]]

output after calibrating Right camera is as follows

    Right Camera Return value :  0.258429588138
    Right Camera Camera Matrix :  [[  2.69094574e+04   0.00000000e+00   1.70580157e+03]
    [  0.00000000e+00   2.69534209e+04   2.55185400e+03]
    [  0.00000000e+00   0.00000000e+00   1.00000000e+00]]
    Right Camera Dist Coeff :  [[-0.1854594   1.89124255  0.00592814 -0.00377697  0.05715002]]

As you can see from the output above, both the return values from `cv2.calibrateCamera` are reasonable.

output after calibrating stereo setup is as follows

    StereoCalib Return Value :  278.98818985
    Rotation Vector :  [[ 0.72415334  0.13289823  0.67671265]
    [ 0.68078781  0.018949   -0.73223554]
    [-0.11013584  0.99094853 -0.07675351]]
    Translation Vector  [[-1.20860215]
    [ 1.23017549]
    [ 2.08116679]]
    Essential Matrix :  [[-1.55231939  1.17960457  1.42948401]
    [ 1.37397347  1.47424592  1.31558743]
    [-1.7136373  -0.18638995  0.05250614]]
    Fundamental Matrix :  [[ -3.15554184e-07   2.39721211e-07   6.99264445e-03]
    [  2.78844610e-07   2.99110045e-07   5.21248054e-03]
    [ -9.54712002e-03  -2.19149124e-03   1.00000000e+00]]

But the return value from stereo calibration is too high.

Params

The flags and criteria i am using in `cv2.stereoCalibrate` are as follows

    flags = cv2.CALIB_FIX_INTRINSIC
    
    criteria = cv2.TERM_CRITERIA_MAX_ITER + cv2.TERM_CRITERIA_EPS, 1000, 1e-6

I would be grateful if somebody can point me where i am doing wrong.

**Comment by sturkmen72** [comment]
could you try a comment or answer on this question http://answers.opencv.org/question/173249/test-tag-sdkdksdjsd/

**Comment by LaurentBerger** [comment]
@parzival2  try delete cookie for answers.opencv.org in your web browser

**Comment by parzival2** [comment]
@sturkmen72 Thank you very much for the post. Yeah i am able to comment on the post.

**Comment by sturkmen72** [comment]
did you delete comment?

**Comment by parzival2** [comment]
@sturkmen72 Yeah. You want me to keep that?

**Comment by sturkmen72** [comment]
no just asked.

**Comment by sturkmen72** [comment]
could you try to answer question ( just type test bla bla.....)

**Comment by parzival2** [comment]
@LaurentBerger I deleted cookies, got the same result.

**Comment by parzival2** [comment]
@sturkmen72 Can you update the question to `Low RMS value when calibrating single camera, while high RMS value in stereoCalibrate` please.
Thanks in advance. 
Sure will do that.

**Comment by sturkmen72** [comment]
you posted a comment i mean an answer

**Comment by parzival2** [comment]
@sturkmen72 I was able to post the answer.

**Comment by sturkmen72** [comment]
do you use windows ? which browser?

**Comment by parzival2** [comment]
@sturkmen72 Yeah, at the moment. I will boot to Ubuntu and try.

**Comment by mshabunin** [comment]
Problem was in word `Canon`, it was in the spam blacklist. @parzival2 , please try to ask your question again, sorry for inconvenience.
