### ISSUE TITLE
Ask new question internal server error

### ISSUE THREAD

**Issue by Crcodlus** [opencv-infrastructure/answers.opencv.org#50]
Every time when I try to ask a question i get the following error:
```
Internal server error
system error log is recorded, error will be fixed as soon as possible
please report the error to the site administrators
```

**Comment by StevenPuttemans** [comment]
@mshabunin it seems this is an issue affecting multiple people, also see #49 

@luug we just switched Askbot backend version and it introduced some issues, will try to get this solved asap!

**Comment by mshabunin** [comment]
@luug, can you post the text of your question here, probably it contains some of blocked words.

**Comment by Crcodlus** [comment]
Sure!
**TITLE** Opencv3.0 LogisticRegression svm scaling
**TEXT**
 I am trying to use `cv::ml::LogisticRegression` to scale the weights given by a SVM.
To train the model I am passing the weight data in the range of [-inf, inf] and the labels  (-1 or 1) to the function  `cv::ml::LogisticRegression::train()`

Till now everything works fine, but when I try to predict a sample by using `cv::ml::LogisticRegression::predict()` I allways get the result -1 or 1. Thus exactly the same result as from the SVM. In my opinion the result should be a probability between 0 and 1.

Used parameters for `cv::ml::LogisticRegression()`:

 - learning rate: 0.001
 - iterations: 1000
 - train method: BATCH
 - regularisation: REG_L2
 - minibatch_size: 1

Am I doing anythin wrong ?

**TAGS**  Opencv3.0 LogisticRegression svm

**Comment by berak** [comment]
@mshabunin , where can we lookup, how the blocking works ?

(and indeed, hardly any spam left in the queue, lately.)

**Comment by StevenPuttemans** [comment]
> (and indeed, hardly any spam left in the queue, lately.)

True and its great!

**Comment by mshabunin** [comment]
@luug, it was the word `weight` 😟. I've disabled the blacklist, so you can post your question now. Sorry for inconvenience.
