### ISSUE TITLE
About issue in opencv or opencv_contrib

### ISSUE THREAD

**Issue by LaurentBerger** [opencv-infrastructure/answers.opencv.org#51]
Hi,
 I think when we post an issue in opencv or opencv_contrib, this text is good : 
"If you have a question rather than reporting a bug please go to http://answers.opencv.org where you get much faster responses.
If you need further assistance please read [How To Contribute](https://github.com/opencv/opencv/wiki/How_to_contribute"

I think first sentence can be in bold 28pt. 

What do you think adding a 👎 to every issue that is a question (answers.opencv or stackoverflow or ....)?

**Comment by sturkmen72** [comment]
i have just put 👎 on https://github.com/opencv/opencv/issues/9547

by this way maybe people realize this place is not for questions

**Comment by StevenPuttemans** [comment]
Well the issue itself is not that straightforward ... problem is that many open source projects actually use github issues as some sort of forum, therefore we will never get rid of this behavior. You can edit the message template when opening a new issue through a PR if you prefer that.

**Comment by berak** [comment]
i'm no fan of the emoji idea, imho it only adds negativism and clutter.

if you feel, you *have* to interfere, rather write a polite, explanatory comment.
