### ISSUE TITLE
Problem with download image in a question

### ISSUE THREAD

**Issue by LaurentBerger** [opencv-infrastructure/answers.opencv.org#57]
Hi,

I have tried to upload a 4Mb image size in a question. I have given the path and I wait 2 minutes : no error message. I have canceled operation using cancel button and then  I'm not able to download a small image in same question.
Anybody can reproduce problem?

Firefox 57.0.4 windows 10

**Comment by berak** [comment]
@LaurentBerger , is it related to [this question](http://answers.opencv.org/question/182708/bottle-detection/) ? 

(and did you mean "upload", not "download" , via the image button ?)

**Comment by LaurentBerger** [comment]
Yes  that is the question ( and upload sorry)
