### ISSUE TITLE
Infinite Karma generation

### ISSUE THREAD

**Issue by NikolasE** [opencv-infrastructure/answers.opencv.org#6]
The karma awarded for accepting my own question in a thread not created by me gives me a +5 Karma. Undoing this only changes my karma by -2. This can be done iteratively to get +3 for each iteration. 
Search for "OpenCV and OpenGL" in my Karma log shows an example
http://answers.opencv.org/users/3134/foobar/?sort=reputation

**Comment by alekcac** [comment]
Thanks! I set new karma rules, now they are +5 and -5 for this scheme.
