### ISSUE TITLE
site down

### ISSUE THREAD

**Issue by berak** [opencv-infrastructure/answers.opencv.org#60]
answers.opencv.org is down

5.9.49.245 can't even be pinged (everything else from opencv.org seems ok.)

**Comment by mshabunin** [comment]
There is a problem with hosting: https://www.hetzner-status.de/en.html (our server is in DC 7). I will submit a ticket.

**Comment by mshabunin** [comment]
Seems to be fixed.
Thank you for report!

**Comment by sturkmen72** [comment]
Answers.opencv.org is DOWN

**Comment by sturkmen72** [comment]
Ok. The site is UP now

**Comment by mshabunin** [comment]
@sturkmen72 , thanks for reporting. We've fixed the issue.
