### ISSUE TITLE
is there a way to block an IP?

### ISSUE THREAD

**Issue by sturkmen72** [opencv-infrastructure/answers.opencv.org#61]
recently we have a lot of spam having the same ip ( ip=172.18.0.4 )

just wonder is there a way to block known spammer IPs

**Comment by berak** [comment]
after watching it for a day, i think, it's a false positive.

simply, *everyone* in the moderation queue has this ip (there's no other, ever).

it's not even a public one. (some reserved ip block owned by ATT)

**Comment by StevenPuttemans** [comment]
> everyone in the moderation queue has this ip

This as already raised like ages ago, and we then came to the same conclusion, that banning that IP is not an option :)

**Comment by mshabunin** [comment]
This IP shows as a side effect of putting services to containers.

We can block posts basing on phrases used in the message. Feel free to suggest candidates for phrases blacklist if they annoy you.

**Comment by berak** [comment]
can email addresses get blacklisted, too ?

(and we should probably start a new issue, collecting phrases / tokens to blacklist)

**Comment by mshabunin** [comment]
There is Slack channel for moderators: https://open-cv.slack.com/messages/G5VN0BXCG/

**Comment by mshabunin** [comment]
>can email addresses get blacklisted, too ?

~Probably not, I did not find this option in AskBot settings.~

**Comment by berak** [comment]
ah, pity. there's a lot of  common ones, like bali-traveller.com or gsasearchengineranker.com.

and ok, blacklist proposals will go to slack.

**Comment by mshabunin** [comment]
>can email addresses get blacklisted, too ?

My mistake, looks like there is a setting:

![image](https://user-images.githubusercontent.com/3304494/44712525-9f1dc480-aab9-11e8-9cd0-0c691313bc71.png)

**Comment by berak** [comment]
ah, good. i'll collect some..

**Comment by StevenPuttemans** [comment]
> ah, good. i'll collect some..

Will keep a list too, maybe do it here with a checklist?

**Comment by StevenPuttemans** [comment]
Lets start

- [ ] @macwarp.com
- [ ] *.gsacaptchabreakerdiscount.com 
- [ ] *.gsasearchengineranker.space
- [ ] @mail.ru

**Comment by berak** [comment]
ok, here's mine:

```
[keywords]
male enhancement
male sex toys
cheap sex toys
Cheap Jerseys china
casino
poker
bitcoin


[email]
dietingadvise.club
aeroshack.com
gsasearchengineranker.*    (multiple tld's)
imgsources.com
mailhex.com
herostartup.com
get-bitcoins.club
get-bitcoins-online.com
coloncleanse.club
captchaeu.info
brainboostingsupplements.org
buyagslist.com
bestwrinklecreamnow.com
captchas.biz
wp-viralclick.com
skillfare.com
get-bitcoins-online.com
```

**Comment by LaurentBerger** [comment]
https://www.stopforumspam.com/downloads
