### ISSUE TITLE
restrictions on users having low karma

### ISSUE THREAD

**Issue by sturkmen72** [opencv-infrastructure/answers.opencv.org#62]
i have just viewed [this post](http://answers.opencv.org/question/195870/videocapure-uncompressed-16-bit-video-stream-y16/) and want to share user's complaint 'PS. It's a bit silly I had to wait 2 days in order to share the answer I found myself...'

also i think no need to restrict new users to upload an image

**Comment by mshabunin** [comment]
>I had to wait 2 days in order to share the answer I found myself

Only users with karma 50 can answer own question immediately, if users with 0 karma will be able to answer the question without delay, they could gain (accept, be accepted) enough karma to bypass captcha and flood the forum.

>no need to restrict new users to upload an image

This setting has been turned off: 
![image](https://user-images.githubusercontent.com/3304494/44745384-43caf100-ab10-11e8-869d-98a8c62747e0.png)

**Comment by sturkmen72** [comment]
thanks
