### ISSUE TITLE
link to opencv.org inside http://answers.opencv.org

### ISSUE THREAD

**Issue by LaurentBerger** [opencv-infrastructure/answers.opencv.org#63]
Hi,

![image](https://user-images.githubusercontent.com/3591626/45098864-30c6ab00-b126-11e8-90fc-72bc8ad0aa4e.png)I'm a little lazy. is it possible when I click here to go opencv.org

**Comment by StevenPuttemans** [comment]
Wait the idea is that you go back to the homepage of the Q&A right?

**Comment by LaurentBerger** [comment]
You have already got house button for this

**Comment by StevenPuttemans** [comment]
Ah indeed, then your request seems valid :dancer:

**Comment by berak** [comment]
i'd rather say: get rid of the house !

**Comment by sturkmen72** [comment]
in my opinion @StevenPuttemans  or @berak  ( even both ) can have Administrator rights. for not stealing @mshabunin's time  about improvements on the forum.

**Comment by mshabunin** [comment]
For some reason this feature does not work:
![image](https://user-images.githubusercontent.com/3304494/45120528-119c3d80-b167-11e8-83b2-6ef93dec8125.png)

I'll try to do it with JS later.

@sturkmen72 , we try to minimize intrusions to the forum engine as it seem to be unsupported for some time. Simple settings modification does not take much time and we still need to discuss them with other users. In my opinion current scheme works well.

**Comment by mshabunin** [comment]
Fixed. Now the logo leads to opencv.org and the house icon to the answers.opencv.org.

**Comment by berak** [comment]
i don't like it. (i'll completely have to retrain my muscle memory)
also, how to get back from the moderation / users pages ?

solved for me personally with script injection:

    logo = document.getElementById("logo")
    logo.href = "http://answers.opencv.org/questions/"

**Comment by mshabunin** [comment]
Restored previous link. Looks like we need a better idea.

**Comment by LaurentBerger** [comment]
C'est vraiment une drôle de manière de procéder. Je pense que j'ai besoin de vacances

**Comment by LaurentBerger** [comment]
@mshabunin I like new links!
![image](https://user-images.githubusercontent.com/3591626/51986380-69359f80-24a0-11e9-8248-9bdfd1539bb4.png)
