### ISSUE TITLE
i would like to become a moderator of OpenCV forum

### ISSUE THREAD

**Issue by AkhilPatoliya** [opencv-infrastructure/answers.opencv.org#67]
Hello,

I would like to join your moderator team of an OpenCV forum and i'm also visit this forum daily since i joined this forum.

**Comment by StevenPuttemans** [comment]
I guess the forum could use some more help, and so do the other moderators, now that some of us underestimated the spare time reduction from moving from PhD to post-doc position >_<

**Comment by mshabunin** [comment]
@AkhilPatoliya , I think we have enough moderators for now. The forum is not very active (~20 questions a day) and spam load has been at low levels lately. Regular users have all necessary moderation mechanisms - votes and flags, main difference of the moderator role is the ability to reject obvious spam posts in the incoming queue. Risk of errors also raise with number of moderatos and the Askbot engine does not have convenient ways of fixing mistakes.
So I'm rejecting your application for now, but we will keep it in mind if situation changes.
