### ISSUE TITLE
answers.opencv.org is missing HTTPS support

### ISSUE THREAD

**Issue by DylanVanAssche** [opencv-infrastructure/answers.opencv.org#68]
Hi,

My browser warned me about this subdomain because of the missing HTTPS suppport. Logging into [answers.opencv.org](http://answers.opencv.org) is a security risk since all the credentials are transferred over the Web in plain text.

Is there a reason why [answers.opencv.org](http://answers.opencv.org) is missing HTTPS? Using Lets Encrypt, we can easily add HTTPS to answers.opencv.org. The project website [opencv.org](https://opencv.org) supports HTTPS out of the box.

Thanks!

**Comment by mshabunin** [comment]
Fixed

**Comment by DylanVanAssche** [comment]
Thanks!
