### ISSUE TITLE
Please not suspended my opencv forum account

### ISSUE THREAD

**Issue by AkhilPatoliya** [opencv-infrastructure/answers.opencv.org#69]
Hello mshabunin ,

I request to you remove my suspended opencv forum account. next time i will guarantee that i will not make a fake upvote on my account. because i need and it's very important for me for my current application and opencv is very usefull for me. 

so again i request you please remove my suspended opencv forum account and allow me to opencv forum.

account name :- Akhil Patoliya
email :- akhilmca2014@gmail.com

Thank you.

**Comment by mshabunin** [comment]
@AkhilPatoliya , clean up after yourself - remove garbage posts and comments and provide here a list of links to fake accounts you've created.

**Comment by AkhilPatoliya** [comment]
Here below is accounts detail.

screen name :- Zafar_0181
email :- zafar011@gmail.com

screen name :- aliza
email :- aliza2008@gmail.com

screen name :- droidcv
email :- akii0181@gmail.com

screen name :- gov.androidopencv
email :- akhil@thefastestmedia.com

screen name :- p_patel
email :- p_patel@gmail.com

screen name :- mariya d'souza 
email :- mari01@gmail.com

**Comment by AkhilPatoliya** [comment]
I have cleanup garage posts which i was created using above all fake accounts.

**Comment by AkhilPatoliya** [comment]
Thank you very much @mshabunin

**Comment by LaurentBerger** [comment]
@mshabunin I propose to reopen this issue : 

http://answers.opencv.org/users/416427/jamie-anderson/?sort=votes
http://answers.opencv.org/users/416419/carman-espanola/?sort=votes
http://answers.opencv.org/users/416385/p_patidar/?sort=votes
http://answers.opencv.org/users/416385/p_patidar/?sort=votes
http://answers.opencv.org/users/416080/patel/?sort=votes
http://answers.opencv.org/users/415976/akii0181/?sort=votes
http://answers.opencv.org/users/415014/jay-sardar/?sort=votes

....

@berak
@sturkmen72

**Comment by sturkmen72** [comment]
@AkhilPatoliya do you have an explanation about this?

**Comment by AkhilPatoliya** [comment]
@mshabunin 
@sturkmen72 
@LaurentBerger

i don't know about this try to understand i have no idea about this because last 15 days i am not login on OpenCV forum because i am on tour. i think someone use my username and password.

**Comment by LaurentBerger** [comment]
@AkhilPatoliya I don't believe you. You upvoted for jamie anderson account and then jamie anderson upvoted for you. As in december :  fake upvote on your account.

**Comment by AkhilPatoliya** [comment]
@LaurentBerger 

No this time i have not any fake upvote in my account. i don't know who is jamie anderson and why he was upvote in my account please try to understand.

**Comment by LaurentBerger** [comment]
I can make same coment about carman-espanola p_patidar, patel, akii0181,jay-sardar. You voted for those user accounts and they voted for you.  It's a real martingale

**Comment by AkhilPatoliya** [comment]
@LaurentBerger

i really don't know about all of these account trust me.

**Comment by AkhilPatoliya** [comment]
@LaurentBerger

See in december when i was created fake upvotes and account i accepted my mistake and remove all the garbage post and fake account but this time i really don't know about this

**Comment by sturkmen72** [comment]
screen name :- droidcv
email :- akii0181@gmail.com

http://answers.opencv.org/users/415976/akii0181
email :- akii0181@yahoo.com

personally i believe @AkhilPatoliya still do some nonusefull activity

**Comment by AkhilPatoliya** [comment]
@sturkmen72 

screen name :- droidcv
email :- akii0181@gmail.com

this account is already suspended and i am not using this account.

**Comment by AkhilPatoliya** [comment]
@LaurentBerger

Please allow me in OpenCV forum and reactivate my current account.

**Comment by mshabunin** [comment]
> commented 2 days ago (Apr 2, 2019)
>i don't know about this try to understand i have no idea about this because last 15 days i am not login on OpenCV forum because i am on tour

>Mar 28 '19 | asked a question
>Mar 29 '19 | commented question

@LaurentBerger , @sturkmen72 , thanks for help, I've suspended several accounts.

**Comment by AkhilPatoliya** [comment]
@mshabunin 

Please do not suspend my openCV account i really need it. i request you.
