### ISSUE TITLE
Feature request: Some rules for tags

### ISSUE THREAD

**Issue by NikolasE** [opencv-infrastructure/answers.opencv.org#7]
Rather a Feature request:
- disallow hashtags like #OpenCV [answers.opencv is not twitter](maybe just strip leading). 
- disallow 'OpenCV' tag  (It's kind of reduntant in this forum)

**Comment by alekcac** [comment]
Good proposal! I plan to update current tags, after that we can add some rules for tags.

**Comment by StevenPuttemans** [comment]
I like this idea very much. The whole forum is cramped with hashtag stuff which doesn't make searching any easier.

**Comment by berak** [comment]
imho, most of those weird hashtags atm come from the autocomplete feature there.

have you ever tried to edit the tags from a question ? it's terrible hard to avoid, that this thing gets in your way, and replaces 'android' with '#android#opencv#java' or such garbage. lexical sort will always put # before anything else. maybe even the database needs a cleanup

**Comment by StevenPuttemans** [comment]
I second that! Editing tags is indeed a creepy buisness, that why I stopped doing so!

**Comment by berak** [comment]
oh, '#' is an 'illegal char'  now, when you enter tags, - good !

**Comment by StevenPuttemans** [comment]
Great!


Verzonden vanaf Samsung Mobile.


-------- Oorspronkelijk bericht --------
Van: berak
Datum:05-02-2015 08:57 (GMT+01:00)
Aan: "opencv-infrastructure/answers.opencv.org"
Cc: Steven Puttemans
Onderwerp: Re: [answers.opencv.org] Feature request: Some rules for tags (#7)


oh, '#' is an 'illegal char' now, when you enter tags, - good !

**Comment by StevenPuttemans** [comment]
This can be closed down, suggestions collected together in #21
