### ISSUE TITLE
Cannot see image in a post

### ISSUE THREAD

**Issue by LaurentBerger** [opencv-infrastructure/answers.opencv.org#70]
in this [post ](http://answers.opencv.org/question/206099/get-this-error-error-215assertion-failed-sizewidth0-sizeheight0-in-function-cvimshow-while-implementing-image-stitching/)I cannot see image using Firefox : 

![capture](https://user-images.githubusercontent.com/3591626/50564989-89036780-0d2a-11e9-8820-6e0c12d1f2a6.JPG)

If I use edge browser  i can see images

If I open link http://answers.opencv.org/upfiles/1546270590599389.jpg there is an error  : 

![image](https://user-images.githubusercontent.com/3591626/50565006-adf7da80-0d2a-11e9-8dd4-8cc8a5f9826e.png)

Title page is 1546270590599389.jpg (Image webp) Can it be problem origin ?

**Comment by alalek** [comment]
Image is not encoded as JPEG. Its format is WebP (by file contents).
BTW, Google Chrome shows page with images.

**Comment by LaurentBerger** [comment]
Ok [firefox 64](https://www.mozilla.org/en-US/firefox/65.0a1/releasenotes/) (my version) does not support webp. But file extension is not webp, it is jpg. File extension is wrong ?

signature is RIFFr  WEBPVP8X

**Comment by StevenPuttemans** [comment]
@LaurentBerger it's only a good habbit to encode jpg extension with jpeg encoding, however it is not a requirement of the jpg container. Same for video, where you can embed mpeg4 encoding in an avi container if you want so.
