### ISSUE TITLE
unable to post question

### ISSUE THREAD

**Issue by rdp** [opencv-infrastructure/answers.opencv.org#71]
When I do it says

Sorry, you cannot ask questions because your account is blocked.
Your account might be blocked in error - please contact the site administrators, if you think so.

http://answers.opencv.org/users/414113/rogerdpack/

Also it would be nice if that message told one *how* to contact the site administrators, as well.... cheers!

**Comment by berak** [comment]
@rdp -- it seems you got blocked "by accident" from a human ;(

easy to revoke (done), apologies for the mishap. 

(but, unfortunately, your previous question (i remember, there was one!) is gone, too)
