### ISSUE TITLE
Require administrator privileges to use VideoCapture(filename)

### ISSUE THREAD

**Issue by laughalot42** [opencv-infrastructure/answers.opencv.org#72]
I have a python program that can open video files when I am signed on as an administrator.  If I am signed on as a standard user, it cannot open the same file.  If I run the IDE (PyCharm) with administrator privileges from the standard user account I can open the file.  I've given full access to everyone for folders containing Anaconda, OpenCV, FFMPEG, and the video files in Windows 10.  Can you suggest what I might be overlooking?

**Comment by alalek** [comment]
This tracker is for infrastructure issues / suggestions only.
