### ISSUE TITLE
topic reported as spam

### ISSUE THREAD

**Issue by sharkyenergy** [opencv-infrastructure/answers.opencv.org#73]
hello, i am not able to post.. my post gets detected as spam.. this is the content of my post that is rejected:

hi,
I was looking for samples on how to crate a stitched image from a video. Basically I have a camera on an axis, moving for about 2 meters. I would need to use this video feed and stitch it toghether to a single image. 
I found several examples of finished programs that show how they are working, but not an explanation on how to archive that.
Thank you

Igor

any idea why?

**Comment by LaurentBerger** [comment]
Hi,
is it this user http://answers.opencv.org/users/416721/sharkyenergy/? Try to post again

**Comment by sharkyenergy** [comment]
yes, this user, but still not working..

**Comment by LaurentBerger** [comment]
Please Try again

**Comment by sharkyenergy** [comment]
nope, still nothing.. spam was detected..

**Comment by LaurentBerger** [comment]
Try in private navigation and copy question How to use cv2.xphoto.inpaint in Python3 and post

**Comment by sharkyenergy** [comment]
nothing.. still spam detected

**Comment by berak** [comment]
i could reproduce it:

http://answers.opencv.org/users/416745/simpleenergy/

(same text, some bar "Spam was detected on your post, sorry for if this is a mistake" showed up on top)

i bet: **energy** in the **username** triggered a spam filter. can you try with "sharkeye" or such ?

**Comment by LaurentBerger** [comment]
No more idea. @alalek @mshabunin  can you try to solve this problem?

**Comment by sharkyenergy** [comment]
well, hate to chagne username as i use it everywhere and have bad memory.. :D would love to be able to post with all my energy.. 💃

**Comment by StevenPuttemans** [comment]
Probably the word sharkyenery should be added to an ignore list :D

**Comment by berak** [comment]
imho, we had enough silly "cheap / clean energy" spam posts to justify the ban ...

**Comment by StevenPuttemans** [comment]
Thats true, but the chance that sharkyenergy in total will be used for spam, might be low 💃

**Comment by sharkyenergy** [comment]
also because i already have it and it is taken.. :D

**Comment by mshabunin** [comment]
@sharkyenergy , I've been able to ask a question on behalf of your user: http://answers.opencv.org/question/211728/looking-for-samples-on-how-to-crate-a-stitched-image-from-a-video/ . Could you please try to add a comment to it?

We don't have any of these words in AskBot spam filter, perhaps it is result of external Akismet filtering. I don't see any parameters or detailed stats there. Not sure how we can control it :disappointed:

**Comment by mshabunin** [comment]
As I can see Akismet can take in account comment content, author, e-mail, IP address and user agent ([code](https://github.com/ASKBOT/askbot-devel/blob/082e651423651d45f6b52dcee51c5f3ac6f2c4a8/askbot/utils/akismet_utils.py#L41-L82)). And it can learn from messages manually marked as spam.

**Comment by sharkyenergy** [comment]
nope, dows not work.. cannot comment..

**Comment by mshabunin** [comment]
OK, I've disabled external spam checking engine for a while. There seem to be not too much spam recently.
