### ISSUE TITLE
My account got blocked for no reason just when I wrote my first question.

### ISSUE THREAD

**Issue by alejandro-colomar** [opencv-infrastructure/answers.opencv.org#74]
"Sorry, you cannot perform this action because your account is blocked.
Your account might be blocked in error - please contact the site administrators, if you think so."

Why? And what do I do?

**Comment by mshabunin** [comment]
Please post here link to your account, e.g. http://answers.opencv.org/users/11975/mshabunin/

**Comment by alejandro-colomar** [comment]
http://answers.opencv.org/users/416716/alcoan/

**Comment by mshabunin** [comment]
Fixed, probably it was blocked by mistake. Did you have any questions asked?

**Comment by alejandro-colomar** [comment]
Yes I did.

I asked about what is the right way to build with -march=native -O3 -flto
