### ISSUE TITLE
moderation queue

### ISSUE THREAD

**Issue by berak** [opencv-infrastructure/answers.opencv.org#8]
a comment from http://answers.opencv.org/users/7/daniil-osokin/ showed up in the moderation queue.

shouldn't only new / low-rep users get moderated ?

**Comment by StevenPuttemans** [comment]
Well since the introduction of the new forum software, it seems that each user needs a first authentication, even the ones who have been around for ages. Better do this than to keep the spam flood comming. I have the idea that the new measures are working out :)

**Comment by alekcac** [comment]
Steven is right.

**Comment by StevenPuttemans** [comment]
@alekcac even if you agree with me, we should still look into the spam generated there daily. It is just huge :D

**Comment by alekcac** [comment]
Hi Steven, 

I have created new issue (https://github.com/opencv-infrastructure/answers.opencv.org/issues/14) about spam. Please write there your issues with SPAM on the website. I will try to help with it.
