### ISSUE TITLE
Account Blocked

### ISSUE THREAD

**Issue by votecoffee** [opencv-infrastructure/answers.opencv.org#83]
My account is blocked on OpenCV.org and I can't open my profile page.  I'm fairly active on stackoverflow.  I started an account for OpenCV.  I answered a question and now my account is blocked.

**Comment by mshabunin** [comment]
@votecoffee , please post the full path to your profile page, e.g. https://answers.opencv.org/users/11975/mshabunin/

**Comment by votecoffee** [comment]
@mshabunin
https://answers.opencv.org/users/432880/votecoffee/

**Comment by LaurentBerger** [comment]
I changed your status to approved user. is it Ok now?

**Comment by votecoffee** [comment]
Yes, thanks
