### ISSUE TITLE
accidently blocked user

### ISSUE THREAD

**Issue by sturkmen72** [opencv-infrastructure/answers.opencv.org#84]
Hi @mshabunin
Sorry i accidently blocked a valid question (after 2020-10-12 14:14:03-0500)
i edited https://answers.opencv.org/question/173360/test-question/ after blocking to leave a sign about time

**Comment by sturkmen72** [comment]
btw i deleted too many unuseful questions recently. just wonder if my activity is logged.

**Comment by mshabunin** [comment]
@sturkmen72 , I can not find the question, lets hope it will be re-asked.

As for activity recording, I think it is being recorded in the database, but there is no convenient UI except this: https://answers.opencv.org/users/16589/sturkmen/?sort=recent
