### ISSUE TITLE
forum.opencv.org: akismet subscription expired

### ISSUE THREAD

**Issue by berak** [opencv-infrastructure/answers.opencv.org#86]
> Akismet API Error: suspended (10402) Your Akismet API key has been suspended. Visit Akismet.com to reactivate your spam filtering subscription.

unless this is solved, **every post** has to be moderated manually ;(

@mshabunin

**Comment by mshabunin** [comment]
We will look into this, thank you for report!

**Comment by berak** [comment]
looks solved now, ty.
